import "./globals.css";
import { Bricolage_Grotesque } from "next/font/google";

import Head from "next/head";

const font = Bricolage_Grotesque({
  subsets: ["latin"],
});

export const metadata = {
  title: "REDEFINE",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          type="text/css"
          charSet="UTF-8"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick.min.css"
        />
        <link
          rel="stylesheet"
          type="text/css"
          href="https://cdnjs.cloudflare.com/ajax/libs/slick-carousel/1.6.0/slick-theme.min.css"
        />
      </head>
      <body className={font.className}>{children}</body>
    </html>
  );
}
